spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: config-eureka-clent
    
eureka:
  instance: 
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
      
---
server:
  port: 7002
spring:
  profiles: test
  application:
    name: config-eureka-clent
    
eureka:
  instance: 
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7002/eureka/